[package]
name = "hilbertizer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bmp = "0.5.0"
fast_hilbert = "1.0.0"
clap = { version = "3.2.8", features = ["derive"]}
